version: "3.5"
services:
 zookeeper:
  image: 'bitnami/zookeeper:latest'
  container_name: zookeeper
  ports:
    - "2181:2181"
  environment:
    - ALLOW_ANONYMOUS_LOGIN=yes

 kafka:
   image: 'bitnami/kafka:latest'
   container_name: kafka
   ports:
     - '9092:9092'
     - '9093:9093'
   environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
   depends_on:
     - zookeeper

 support:
  build: .
  container_name: support
  environment:
    KAFKA_SERVER: kafka:9092
  ports:
    - "8084:8084"
  depends_on:
    - kafka

 technical-support:
  build: ../technical-support/
  container_name: technical-support
  environment:
    KAFKA_SERVER: kafka:9092
  depends_on:
    - kafka
