version: "3"
services:
 mongo-movies:
  image: mongo:4.2.5
  container_name: mongo-movies
  environment:
    MONGO_INITDB_DATABASE: movies
  volumes:
   - ./resources/mongodb:/docker-entrypoint-initdb.d

 movies:
  build: ./movies
  container_name: movies
  ports:
    - "8081:8080"
  environment:
    MONGO_HOST: mongo-movies
  depends_on:
    - mongo-movies
