version: "3"
services:
 mongo-ranking:
  image: mongo:4.2.5
  container_name: mongo-ranking
  environment:
    MONGO_INITDB_DATABASE: ranking
  volumes:
   - ./resources/mongodb:/docker-entrypoint-initdb.d

 ranking:
  build: .
  container_name: ranking
  ports:
    - "8082:8080"
  environment:
    MONGO_HOST: mongo-ranking
  depends_on:
    - mongo-ranking
