version: "3"
services:
 mongo-room:
  image: mongo:4.2.5
  container_name: mongo-room
  environment:
    MONGO_INITDB_DATABASE: room
  volumes:
   - ./resources/mongodb:/docker-entrypoint-initdb.d

 room:
  build: .
  container_name: room
  ports:
    - "8081:8080"
  environment:
    MONGO_HOST: mongo-room
  depends_on:
    - mongo-room
